// actionTypes.js
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const ADD_TO_CART_DUPLICATE = "ADD_TO_CART_DUPLICATE";



// Action types for getting the user's cart
export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';



// actionTypes.js
export const INCREMENT_ITEM_REQUEST = "INCREMENT_ITEM_REQUEST";
export const INCREMENT_ITEM_SUCCESS = "INCREMENT_ITEM_SUCCESS";
export const INCREMENT_ITEM_FAILURE = "INCREMENT_ITEM_FAILURE";

export const DECREMENT_ITEM_REQUEST = "DECREMENT_ITEM_REQUEST";
export const DECREMENT_ITEM_SUCCESS = "DECREMENT_ITEM_SUCCESS";
export const DECREMENT_ITEM_FAILURE = "DECREMENT_ITEM_FAILURE";




// actionTypes.js
export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE';
